source: /app
paths:
  uploads: uploads
  static: ''
  collections: ''
  data: ''
  layouts:
collections_config:
  home:
    path: /app
    output: false
    url:
    filter:
      base: all
      include: []
      exclude:
    parse_branch_index:
    name: Home
    description: ''
    icon: home
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas: {}
    schema_key:
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: NZ-CHAT
